name: Bump version
run-name: Bump "${{ inputs.version_part }}" version

on:
  workflow_dispatch:
    inputs:
      version_part:
        type: choice
        description: Part of the version to bump.
        options:
          - Major
          - Minor
          - Patch
        default: Patch
        required: true

permissions:
  contents: read

concurrency:
  group: bump-version-main

jobs:
  bump_version:
    name: Initiate version bump
    runs-on: ubuntu-latest
    environment:
      name: version-bump
      deployment: false

    steps:
      - name: Ensure branch is main
        if: github.ref != 'refs/heads/main'
        run: |
          echo "::error::This workflow can only be run from the main branch."
          exit 1

      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.VERSION_BUMP_CLIENT_ID }}
          private-key: ${{ secrets.VERSION_BUMP_PRIVATE_KEY }}

      - name: Checkout main
        uses: actions/checkout@v7.0.1
        with:
          ref: main
          token: ${{ steps.app-token.outputs.token }}

      - name: Bumping "${{ inputs.version_part }}"
        working-directory: scripts
        shell: pwsh
        run: |
          if ('${{ inputs.version_part }}' -ne 'Patch') {
            ./bump-version.ps1 -${{ inputs.version_part }}
          } else {
            ./bump-version.ps1
          }

      # Bot identity found in the original GitHub Actions.
      # Source: https://github.com/actions/checkout/pull/1184
      - name: Commit and push version bump to main
        env:
          NAME: "github-actions[bot]"
          EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          VERSION_PART: ${{ inputs.version_part }}
        run: |
          git config user.name ${{ env.NAME }} 
          git config user.email ${{ env.EMAIL }}
          git add -u -- src

          if git diff --cached --quiet; then
            echo "::error::No version changes to commit."
            exit 1
          fi

          part="${VERSION_PART,,}"
          git commit -m "chore: bump ${part} version"
          git push origin HEAD:main