name: Bump version
run-name: Bump ${{ inputs.version_type }} version

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: Part of the version to bump.
        options:
          - Major
          - Minor
          - Patch
        default: Patch
        required: true

permissions:
  contents: write

jobs:
  bump_version:
    name: Initiate version bump
    runs-on: ubuntu-latest

    steps:
      - name: Ensure branch is main
        if: github.ref != 'refs/heads/main'
        run: |
          echo "::error::This workflow can only be run from the main branch."
          exit 1

      - name: Checkout main
        uses: actions/checkout@v7.0.1
        with:
          ref: main

      - name: Bumping "${{ inputs.version_type }}"
        working-directory: scripts
        shell: pwsh
        run: ./bump-version.ps1 -${{ inputs.version_type }}

      # Bot identity found in the original GitHub Actions.
      # Source: https://github.com/actions/checkout/pull/1184
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
 
          if git diff --cached --quiet; then
            echo "No version changes to commit."
            exit 0
          fi

          git commit -m "chore: bump ${{ inputs.version_type }} version"
          git push